import type { Metadata } from "next";
import "@fontsource/salsa";
import "./globals.css";
import Header from "@/containers/Header";

export const metadata: Metadata = {
  title: "Clips Cloud | A place to do everything with viral clips",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative text-gray-300 bg-black min-h-screen h-full`}>
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
